package JPA_hibernate.EShop.model;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;
import java.util.Objects;

@MappedSuperclass
public abstract class IdAutoGeneratedEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int Id;

    public IdAutoGeneratedEntity() {
    }

    public IdAutoGeneratedEntity(int id) {
        Id = id;
    }

    public int getId() {
        return Id;
    }

    public void setId(int id) {
        Id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        IdAutoGeneratedEntity that = (IdAutoGeneratedEntity) o;
        return Id == that.Id;
    }

    @Override
    public int hashCode() {
        return Objects.hash(Id);
    }
}
